docs:
	pdflatex --output-directory=./TeX/ ./TeX/nanosoc_testboard.tex
	pdflatex --output-directory=./TeX/ ./TeX/nanosoc_testboard.tex
	mv ./TeX/nanosoc_testboard.pdf ./nanosoc_testboard.pdf
	rm ./TeX/nanosoc_testboard.aux
	rm ./TeX/nanosoc_testboard.log
	rm ./TeX/nanosoc_testboard.out
	rm ./TeX/nanosoc_testboard.toc
